"use client";

import { useState } from "react";
import Image from "next/image";
import { Award, Check, Clock, Dumbbell, Mail, MapPin, Menu, Phone, Play, Quote, Star, Users, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Sheet, SheetContent, SheetDescription, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { ThemeToggle } from "@/components/layout/ThemeToggle";
import { ContactForm } from "@/components/shared/ContactForm";
import { SocialLinks } from "@/components/shared/SocialLinks";
import { StarRating } from "@/components/shared/StarRating";
import { WhatsAppButton, WhatsAppInline } from "@/components/shared/WhatsAppButton";
import { BrandLogo } from "@/components/templates/BrandLogo";
import { getGoogleMapsSearchUrl } from "@/lib/contact-links";
import { displayNumber, isMissingNumber } from "@/lib/content-placeholders";
import { submitLeadToGoogleSheet } from "@/lib/googleSheets";
import { cn, getInitials } from "@/lib/utils";
import type { GymConfig } from "@/types";

const links = [
  ["About", "#about"], ["Membership", "#membership"], ["Trainers", "#trainers"],
  ["Classes", "#classes"], ["Gallery", "#gallery"], ["Contact", "#contact"],
] as const;

function planHref(value?: string) {
  if (!value?.trim()) return "#contact";
  if (value.startsWith("#")) return value;
  try { const url = new URL(value); return ["http:", "https:"].includes(url.protocol) ? url.toString() : "#contact"; } catch { return "#contact"; }
}

export function ClassicGymTemplate({ config }: { config: GymConfig }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [category, setCategory] = useState("All");
  const categories = ["All", ...Array.from(new Set(config.galleryImages.map((image) => image.category).filter(Boolean)))];
  const gallery = category === "All" ? config.galleryImages : config.galleryImages.filter((image) => image.category === category);
  const contactDetails = [
    { icon: Phone, label: "Phone", value: config.phone, href: `tel:${config.phone}` },
    { icon: Mail, label: "Email", value: config.email, href: `mailto:${config.email}` },
    { icon: MapPin, label: "Address", value: `${config.address}, ${config.city}`, href: getGoogleMapsSearchUrl(config.address, config.city) },
  ];
  const heroStats = [
    { icon: Users, value: "1,200+", label: "Active Members" },
    { icon: Award, value: "15+", label: "Expert Trainers" },
    { icon: Star, value: "4.9★", label: "Member Rating" },
  ];

  return <div className="flex min-h-screen flex-col bg-background text-foreground">
    <header className="fixed top-0 z-50 w-full bg-white/95 shadow-sm backdrop-blur dark:bg-black/95">
      <nav className="container mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <a href="#hero" className="flex items-center gap-2 text-xl font-extrabold"><BrandLogo src={config.logo} alt={config.name} size={32} className="h-8 w-8 rounded-lg object-contain" fallback={<span className="flex h-8 w-8 items-center justify-center rounded-lg bg-orange-500"><Dumbbell className="h-4 w-4 text-white" /></span>} />{config.name}</a>
        <div className="hidden items-center gap-1 md:flex">{links.map(([label, href]) => <a key={href} href={href} className="rounded-md px-3 py-2 text-sm font-medium text-foreground/80 transition-colors hover:text-orange-500 dark:text-white/80">{label}</a>)}</div>
        <div className="flex items-center gap-2"><ThemeToggle className="hover:bg-black/5 dark:text-white dark:hover:bg-white/10" /><Button asChild size="sm" className="hidden bg-orange-500 text-white hover:bg-orange-600 md:flex"><a href="#membership">Join Now</a></Button><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="md:hidden">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</Button></SheetTrigger><SheetContent side="right" className="w-72 bg-black text-white"><SheetTitle className="sr-only">Gym navigation</SheetTitle><SheetDescription className="sr-only">Navigate through the Gym website sections.</SheetDescription><nav className="mt-8 flex flex-col gap-2">{links.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)} className="rounded-md px-4 py-3 text-white/80 hover:bg-white/10 hover:text-orange-400">{label}</a>)}<Button asChild className="mt-4 bg-orange-500 hover:bg-orange-600" onClick={() => setMenuOpen(false)}><a href="#membership">Join Now</a></Button></nav></SheetContent></Sheet></div>
      </nav>
    </header>

    <main>
      <section id="hero" className="relative flex min-h-screen items-center overflow-hidden"><Image src={config.heroImage} alt="Gym hero" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/60 to-black/30" /><div className="relative container mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8"><div className="max-w-2xl"><Badge className="mb-6 border-orange-500/40 bg-orange-500/20 text-orange-400">🔥 Join 1,200+ Members</Badge><h1 className="mb-6 whitespace-pre-line text-5xl font-black leading-none tracking-tight text-white sm:text-6xl lg:text-7xl">{config.heroTitle}</h1><p className="mb-10 max-w-xl text-lg leading-relaxed text-white/80">{config.heroSubtitle}</p><div className="flex flex-col gap-4 sm:flex-row"><Button asChild size="xl" className="gap-2 bg-orange-500 font-bold text-white hover:bg-orange-600"><a href="#membership">{config.heroCtaText}<Zap className="h-5 w-5" /></a></Button><Button asChild size="xl" variant="outline" className="gap-2 border-white/30 bg-white/15 text-white hover:bg-white/25"><a href="#classes"><Play className="h-5 w-5 fill-white" />View Schedule</a></Button></div><div className="mt-16 grid grid-cols-3 gap-6 border-t border-white/20 pt-8">{heroStats.map(({ icon: StatIcon, value, label }) => <div key={label}><StatIcon className="mb-1 h-5 w-5 text-orange-400" /><div className="text-2xl font-extrabold text-white">{value}</div><div className="text-xs text-white/60">{label}</div></div>)}</div></div></div></section>

      <section id="about" className="section-padding bg-background template-section"><div className="container mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="relative h-[480px]"><Image src={config.aboutImage} alt="Gym interior" fill sizes="(max-width: 1023px) 100vw, 50vw" className="rounded-2xl object-cover shadow-2xl" /><div className="absolute -bottom-6 -right-6 hidden rounded-2xl bg-orange-500 p-6 text-white shadow-xl lg:block"><div className="text-4xl font-black">10+</div><div className="text-sm">Years of Excellence</div></div></div><div><span className="text-sm font-semibold uppercase tracking-widest text-orange-500">About Us</span><h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">More Than a Gym — <span className="text-orange-500">A Lifestyle</span></h2><p className="mt-4 leading-relaxed text-muted-foreground">{config.description}</p><p className="mt-4 leading-relaxed text-muted-foreground">Founded with a single mission — to make world-class fitness accessible to everyone in {config.city}. Whether you&apos;re a first-timer or a seasoned athlete, we have everything you need to reach your goals.</p><div className="mt-8 grid grid-cols-2 gap-3">{config.amenities.map((amenity) => <div key={amenity} className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 shrink-0 text-orange-500" />{amenity}</div>)}</div></div></div></section>

      <section id="membership" className="section-padding bg-zinc-950 template-section"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto mb-12 max-w-2xl text-center text-white"><span className="text-sm font-semibold uppercase tracking-widest text-orange-400">Membership Plans</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Choose Your Path</h2><p className="mt-3 text-white/60">Flexible plans designed for every fitness goal and budget. No contracts — cancel anytime.</p></div><div className="grid gap-8 md:grid-cols-3">{config.membership.map((plan) => { const href = planHref(plan.link); const external = href.startsWith("http"); return <article key={plan.id} className={cn("relative flex flex-col overflow-hidden rounded-2xl p-8", plan.highlighted ? "bg-orange-500 text-white shadow-2xl" : "bg-zinc-800 text-white")}><>{plan.badge && <Badge className="absolute right-4 top-4 bg-white text-orange-500">{plan.badge}</Badge>}</><h3 className="text-xl font-extrabold">{plan.name}</h3><p className="mt-1 text-sm opacity-80">{plan.description}</p><div className="my-7"><span className="text-xs opacity-70">{plan.currency} </span><span className="text-4xl font-black">{displayNumber(plan.price)}</span><div className="text-xs opacity-70">per {plan.period}</div></div><ul className="mb-8 flex-1 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-sm"><Check className="mt-0.5 h-4 w-4 shrink-0" />{feature}</li>)}</ul><Button asChild size="lg" className={cn("w-full font-bold", plan.highlighted ? "bg-white text-orange-500 hover:bg-white/90" : "bg-orange-500 text-white hover:bg-orange-600")}><a href={href} target={external ? "_blank" : undefined} rel={external ? "noopener noreferrer" : undefined}>Get Started</a></Button></article>; })}</div></div></section>

      <section id="trainers" className="section-padding bg-background template-section"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 text-center"><span className="text-sm font-semibold uppercase tracking-widest text-orange-500">Our Trainers</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Train With the Best</h2></div><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{config.trainers.map((trainer) => <article key={trainer.id} className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="relative h-64"><Image src={trainer.image} alt={trainer.name} fill sizes="(max-width: 639px) 100vw, (max-width: 1023px) 50vw, 25vw" className="object-cover object-top" /><Badge className="absolute bottom-4 left-4 bg-orange-500 text-white">{trainer.experience} experience</Badge></div><div className="p-5"><h3 className="text-lg font-bold">{trainer.name}</h3><p className="mt-0.5 text-sm font-medium text-orange-500">{trainer.specialization}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{trainer.bio}</p><div className="mt-4 space-y-1">{trainer.certifications.map((cert) => <div key={cert} className="flex gap-1 text-xs text-muted-foreground"><Award className="h-3 w-3 text-orange-400" />{cert}</div>)}</div></div></article>)}</div></div></section>

      <section id="classes" className="section-padding bg-muted/40 template-section"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 text-center"><span className="text-sm font-semibold uppercase tracking-widest text-orange-500">Class Schedule</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Weekly Class Timetable</h2></div><div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr className="border-b bg-muted/50">{["Class", "Day", "Time", "Duration", "Instructor", "Level", "Spots"].map((heading) => <th key={heading} className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-muted-foreground">{heading}</th>)}</tr></thead><tbody className="divide-y">{config.classes.map((item) => <tr key={item.id} className="transition-colors hover:bg-muted/30"><td className="px-6 py-4 text-sm font-semibold">{item.name}</td><td className="px-6 py-4 text-sm text-muted-foreground">{item.day}</td><td className="px-6 py-4 text-sm"><span className="flex gap-1.5"><Clock className="h-3.5 w-3.5 text-orange-500" />{item.time}</span></td><td className="px-6 py-4 text-sm text-muted-foreground">{item.duration}</td><td className="px-6 py-4 text-sm">{item.instructor}</td><td className="px-6 py-4"><span className="rounded-full bg-orange-100 px-2.5 py-0.5 text-xs text-orange-700 dark:bg-orange-900/30 dark:text-orange-400">{item.level}</span></td><td className="px-6 py-4 text-sm"><span className="flex gap-1"><Users className="h-3.5 w-3.5 text-muted-foreground" />{isMissingNumber(item.spots) ? "[Missing number]" : `${item.spots} left`}</span></td></tr>)}</tbody></table></div></div></div></section>

      <section id="testimonials" className="section-padding bg-zinc-950 template-section"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 text-center text-white"><span className="text-sm font-semibold uppercase tracking-widest text-orange-400">Success Stories</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Real Results, Real People</h2></div><div className="grid gap-6 md:grid-cols-3">{config.testimonials.map((testimonial) => <figure key={testimonial.id} className="rounded-2xl bg-zinc-800 p-8"><Quote className="mb-4 h-8 w-8 text-orange-500" /><blockquote className="mb-6 text-sm leading-relaxed text-white/80">“{testimonial.content}”</blockquote><figcaption className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-orange-500 font-bold text-white">{getInitials(testimonial.name)}</span><div><div className="font-bold text-white">{testimonial.name}</div><div className="text-xs text-white/50">{testimonial.role}</div><StarRating rating={testimonial.rating} size="sm" className="mt-1" /></div></figcaption></figure>)}</div></div></section>

      <section id="gallery" className="section-padding bg-background template-section"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-10 text-center"><span className="text-sm font-semibold uppercase tracking-widest text-orange-500">Gallery</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">See Our World-Class Facility</h2></div><div className="mb-8 flex flex-wrap justify-center gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item as string)} className={cn("rounded-full px-5 py-2 text-sm font-medium", category === item ? "bg-orange-500 text-white" : "border bg-card text-muted-foreground hover:border-orange-500 hover:text-orange-500")}>{item}</button>)}</div><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{gallery.map((image, index) => <figure key={image.id} className={cn("group relative overflow-hidden rounded-xl", index === 0 ? "col-span-2 aspect-[4/3] md:row-span-2 md:aspect-auto" : "aspect-[4/3]")}><Image src={image.src} alt={image.alt} fill sizes="(max-width: 767px) 50vw, (max-width: 1023px) 33vw, 25vw" className="object-cover transition-transform duration-500 group-hover:scale-105" />{image.category && <figcaption className="absolute bottom-3 left-3 rounded-full bg-orange-500 px-2.5 py-1 text-xs text-white opacity-0 transition-opacity group-hover:opacity-100">{image.category}</figcaption>}</figure>)}</div></div></section>

      <section id="contact" className="section-padding bg-background template-section"><div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 text-center"><span className="text-sm font-semibold uppercase tracking-widest text-orange-500">Get In Touch</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Start Your Journey Today</h2></div><div className="grid gap-12 lg:grid-cols-2"><div className="space-y-4">{contactDetails.map(({ icon: Icon, label, value, href }) => <a key={label} href={href!} target={href?.startsWith("http") ? "_blank" : undefined} rel={href?.startsWith("http") ? "noopener noreferrer" : undefined} className="flex gap-4 rounded-xl border bg-card p-5 transition-colors hover:border-orange-500"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-orange-500/10 text-orange-500"><Icon className="h-5 w-5" /></span><span><span className="block text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</span><span className="mt-0.5 block font-medium">{value}</span></span></a>)}<div className="rounded-2xl bg-gradient-to-br from-orange-500 to-red-600 p-6 text-white"><h3 className="text-lg font-bold">Free Trial Session!</h3><p className="mb-4 mt-2 text-sm text-white/80">Message us on WhatsApp to claim your free 1-day trial. No commitment required.</p><WhatsAppInline config={config.whatsapp} label="Claim Free Trial" className="w-full justify-center" /></div></div><div className="rounded-2xl border bg-card p-8 shadow-sm"><h3 className="mb-6 text-xl font-bold">Send Us a Message</h3><ContactForm accentColor="#f97316" onSubmit={({ data, honeypot }) => submitLeadToGoogleSheet({ template: "gym", businessName: config.name, data, honeypot })} /></div></div></div></section>
    </main>
    <footer className="bg-zinc-950 py-12 text-white"><div className="container mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 md:grid-cols-3 lg:px-8"><div><div className="flex items-center gap-2 text-xl font-extrabold"><BrandLogo src={config.logo} alt={config.name} size={24} className="h-6 w-6 rounded object-contain" fallback={<Dumbbell className="h-5 w-5 text-orange-500" />} />{config.name}</div><p className="mt-4 text-sm text-white/50">{config.tagline}</p><SocialLinks links={config.socialLinks} className="mt-4 flex gap-3" linkClassName="text-white/50 hover:text-orange-400" /></div><div><p className="mb-4 text-sm font-semibold uppercase tracking-wider text-white/70">Quick Links</p>{links.map(([label, href]) => <a key={href} href={href} className="block py-1 text-sm text-white/60 hover:text-orange-400">{label}</a>)}</div><div><p className="mb-4 text-sm font-semibold uppercase tracking-wider text-white/70">Contact</p><div className="space-y-2 text-sm text-white/60"><p>{config.phone}</p><p>{config.email}</p><p>{config.address}</p><p>{config.city}</p></div></div></div></footer>
    <WhatsAppButton config={config.whatsapp} />
  </div>;
}
